### ISSUE TITLE
0.4 broken

### ISSUE THREAD

**Issue by sengaya** [AlexanderThaller/prometheus_exporter#1]
The 0.4 version does not return any data (empty site). The 0.3 version works as expected. Tested with both of the examples.

**Comment by AlexanderThaller** [comment]
Hello sengaya,
I forgot to update the depenencies in the examples. They where using a different (older) version of the prometheus crate so the global registrar for metrics was different from the crate so no metrics where registered in a way the crate could see.

I updated the dependencies of the examples in commit https://github.com/AlexanderThaller/prometheus_exporter/commit/629dc5e8be096bc18afa078026b70fb54a73e42e which fixed it for me.

Hope that helped. Sorry about the confusion. Probably should make sure that I keep the dependencies in sync somehow.

**Comment by AlexanderThaller** [comment]
I also updated the readme to make that fact more clear.

**Comment by sengaya** [comment]
Thanks for the update and the explanation. Works as expected.
