### ISSUE TITLE
Promethues version 0.11

### ISSUE THREAD

**Issue by fggarcia** [AlexanderThaller/prometheus_exporter#11]
Hi @AlexanderThaller .

Do you plan to support crate prometheus 0.11?

Thanks!

**Comment by AlexanderThaller** [comment]
Yeah should be pretty easy to update. I still haven't decided if I want to do a mayor release when I bump the preometheus dependency. I think it would make sense.

**Comment by AlexanderThaller** [comment]
I have no Idea why github autoclosed this issue :D

Should be fixed now with version 0.8.0.

Thank you!
