### ISSUE TITLE
Can we please cut a new release of prometheus_exporter?

### ISSUE THREAD

**Issue by siris** [AlexanderThaller/prometheus_exporter#30]
Summary
=======

Recently I have been developing a Prometheus Exporter using this Rust library and came across this error after following the examples:
```
error[E0599]: no method named `with_registry` found for struct `prometheus_exporter::Builder` in the current scope
  --> src/main.rs:62:14
   |
62 |     exporter.with_registry(custom_registry);
   |              ^^^^^^^^^^^^^
```

It looks like some features have recently been merged in #23 and #26 such as using a custom registry, which seems required for labeled Prometheus metrics (Or is there a different way to create labeled Prometheus metrics without a custom Registry?)

Is is possible to cut a new `prometheus_exporter` crate release to include these features?

**Comment by AlexanderThaller** [comment]
Published https://github.com/AlexanderThaller/prometheus_exporter/releases/tag/0.8.5
